// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ChatListData, ChatListResponses, ChatsListData, ChatsListResponses, ChatsRetrieveData, ChatsRetrieveResponses, LaptopsListData, LaptopsListResponses, LaptopsRetrieveData, LaptopsRetrieveResponses, ReviewsDestroyData, ReviewsDestroyResponses, ReviewsListData, ReviewsListResponses, ReviewsPartialUpdateData, ReviewsPartialUpdateResponses, ReviewsRetrieveData, ReviewsRetrieveResponses, ReviewsUpdateData, ReviewsUpdateResponses, TokenCreateData, TokenCreateResponses, TokenRefreshCreateData, TokenRefreshCreateResponses, TokenVerifyCreateData, TokenVerifyCreateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const chatList = <ThrowOnError extends boolean = false>(options: Options<ChatListData, ThrowOnError>) => (options.client ?? client).get<ChatListResponses, unknown, ThrowOnError>({ url: '/api/chat/{channel_id}', ...options });

export const chatsList = <ThrowOnError extends boolean = false>(options?: Options<ChatsListData, ThrowOnError>) => (options?.client ?? client).get<ChatsListResponses, unknown, ThrowOnError>({ url: '/api/chats/', ...options });

export const chatsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ChatsRetrieveData, ThrowOnError>) => (options.client ?? client).get<ChatsRetrieveResponses, unknown, ThrowOnError>({ url: '/api/chats/{channel_id}/', ...options });

export const laptopsList = <ThrowOnError extends boolean = false>(options?: Options<LaptopsListData, ThrowOnError>) => (options?.client ?? client).get<LaptopsListResponses, unknown, ThrowOnError>({ url: '/api/laptops/', ...options });

export const laptopsRetrieve = <ThrowOnError extends boolean = false>(options: Options<LaptopsRetrieveData, ThrowOnError>) => (options.client ?? client).get<LaptopsRetrieveResponses, unknown, ThrowOnError>({ url: '/api/laptops/{id}/', ...options });

export const reviewsList = <ThrowOnError extends boolean = false>(options?: Options<ReviewsListData, ThrowOnError>) => (options?.client ?? client).get<ReviewsListResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reviews',
    ...options
});

export const reviewsDestroy = <ThrowOnError extends boolean = false>(options: Options<ReviewsDestroyData, ThrowOnError>) => (options.client ?? client).delete<ReviewsDestroyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reviews/{id}',
    ...options
});

export const reviewsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ReviewsRetrieveData, ThrowOnError>) => (options.client ?? client).get<ReviewsRetrieveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reviews/{id}',
    ...options
});

export const reviewsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ReviewsPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<ReviewsPartialUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reviews/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const reviewsUpdate = <ThrowOnError extends boolean = false>(options: Options<ReviewsUpdateData, ThrowOnError>) => (options.client ?? client).put<ReviewsUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/reviews/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
 * token pair to prove the authentication of those credentials.
 */
export const tokenCreate = <ThrowOnError extends boolean = false>(options: Options<TokenCreateData, ThrowOnError>) => (options.client ?? client).post<TokenCreateResponses, unknown, ThrowOnError>({
    url: '/api/token/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
 * token if the refresh token is valid.
 */
export const tokenRefreshCreate = <ThrowOnError extends boolean = false>(options: Options<TokenRefreshCreateData, ThrowOnError>) => (options.client ?? client).post<TokenRefreshCreateResponses, unknown, ThrowOnError>({
    url: '/api/token/refresh/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Takes a token and indicates if it is valid.  This view provides no
 * information about a token's fitness for a particular use.
 */
export const tokenVerifyCreate = <ThrowOnError extends boolean = false>(options: Options<TokenVerifyCreateData, ThrowOnError>) => (options.client ?? client).post<TokenVerifyCreateResponses, unknown, ThrowOnError>({
    url: '/api/token/verify/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
