// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Chat = {
  channel_id: number;
  readonly chat_posts: string;
  username?: string | null;
  title: string;
  description?: string | null;
  member_count?: number | null;
  is_verified?: boolean;
  is_private?: boolean;
  is_active?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
  profile_photo: string;
  language?: string | null;
  category?: string | null;
};

export type LaptopImage = {
  image: string;
};

export type LaptopPost = {
  readonly uuid: string;
  title: string;
  storage?: string | null;
  processor?: string | null;
  graphics?: string | null;
  display?: string | null;
  ram?: string | null;
  battrey?: string | null;
  status?: string | null;
  description?: string | null;
  price?: string | null;
  channel_name: string;
  posted_at: string;
  readonly reviews: Array<Review>;
  readonly average_rating: string;
  readonly images: Array<LaptopImage>;
  color?: string | null;
  readonly channel: string;
  readonly simmilar_items: string;
};

export type PaginatedChatList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Chat>;
};

export type PaginatedLaptopPostList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<LaptopPost>;
};

export type PaginatedReviewList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Review>;
};

export type PatchedReview = {
  readonly id?: number;
  readonly user?: string;
  rating?: number;
  comment?: string | null;
  readonly created_at?: string;
};

export type Review = {
  readonly id: number;
  readonly user: string;
  rating: number;
  comment?: string | null;
  readonly created_at: string;
};

export type TokenObtainPair = {
  email: string;
  password: string;
  readonly access: string;
  readonly refresh: string;
};

export type TokenRefresh = {
  readonly access: string;
  refresh: string;
};

export type TokenVerify = {
  token: string;
};

export type ChatWritable = {
  channel_id: number;
  username?: string | null;
  title: string;
  description?: string | null;
  member_count?: number | null;
  is_verified?: boolean;
  is_private?: boolean;
  is_active?: boolean;
  profile_photo: string;
  language?: string | null;
  category?: string | null;
};

export type LaptopPostWritable = {
  title: string;
  storage?: string | null;
  processor?: string | null;
  graphics?: string | null;
  display?: string | null;
  ram?: string | null;
  battrey?: string | null;
  status?: string | null;
  description?: string | null;
  price?: string | null;
  channel_name: string;
  posted_at: string;
  color?: string | null;
};

export type PaginatedChatListWritable = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<ChatWritable>;
};

export type PaginatedLaptopPostListWritable = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<LaptopPostWritable>;
};

export type PaginatedReviewListWritable = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<ReviewWritable>;
};

export type PatchedReviewWritable = {
  rating?: number;
  comment?: string | null;
};

export type ReviewWritable = {
  rating: number;
  comment?: string | null;
};

export type TokenRefreshWritable = {
  refresh: string;
};

export type ChatListData = {
  body?: never;
  path: {
    channel_id: string;
  };
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
  };
  url: "/api/chat/{channel_id}";
};

export type ChatListResponses = {
  200: PaginatedLaptopPostList;
};

export type ChatListResponse = ChatListResponses[keyof ChatListResponses];

export type ChatsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
  };
  url: "/api/chats/";
};

export type ChatsListResponses = {
  200: PaginatedChatList;
};

export type ChatsListResponse = ChatsListResponses[keyof ChatsListResponses];

export type ChatsRetrieveData = {
  body?: never;
  path: {
    /**
     * A unique value identifying this telegram chat.
     */
    channel_id: number;
  };
  query?: never;
  url: "/api/chats/{channel_id}/";
};

export type ChatsRetrieveResponses = {
  200: Chat;
};

export type ChatsRetrieveResponse =
  ChatsRetrieveResponses[keyof ChatsRetrieveResponses];

export type LaptopsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
  };
  url: "/api/laptops/";
};

export type LaptopsListResponses = {
  200: PaginatedLaptopPostList;
};

export type LaptopsListResponse =
  LaptopsListResponses[keyof LaptopsListResponses];

export type LaptopsRetrieveData = {
  body?: never;
  path: {
    /**
     * A unique integer value identifying this laptop post.
     */
    id: number;
  };
  query?: never;
  url: "/api/laptops/{id}/";
};

export type LaptopsRetrieveResponses = {
  200: LaptopPost;
};

export type LaptopsRetrieveResponse =
  LaptopsRetrieveResponses[keyof LaptopsRetrieveResponses];

export type ReviewsListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * A page number within the paginated result set.
     */
    page?: number;
  };
  url: "/api/reviews";
};

export type ReviewsListResponses = {
  200: PaginatedReviewList;
};

export type ReviewsListResponse =
  ReviewsListResponses[keyof ReviewsListResponses];

export type ReviewsDestroyData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/reviews/{id}";
};

export type ReviewsDestroyResponses = {
  /**
   * No response body
   */
  204: void;
};

export type ReviewsDestroyResponse =
  ReviewsDestroyResponses[keyof ReviewsDestroyResponses];

export type ReviewsRetrieveData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/reviews/{id}";
};

export type ReviewsRetrieveResponses = {
  200: Review;
};

export type ReviewsRetrieveResponse =
  ReviewsRetrieveResponses[keyof ReviewsRetrieveResponses];

export type ReviewsPartialUpdateData = {
  body?: PatchedReviewWritable;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/reviews/{id}";
};

export type ReviewsPartialUpdateResponses = {
  200: Review;
};

export type ReviewsPartialUpdateResponse =
  ReviewsPartialUpdateResponses[keyof ReviewsPartialUpdateResponses];

export type ReviewsUpdateData = {
  body: ReviewWritable;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/reviews/{id}";
};

export type ReviewsUpdateResponses = {
  200: Review;
};

export type ReviewsUpdateResponse =
  ReviewsUpdateResponses[keyof ReviewsUpdateResponses];

export type TokenCreateData = {
  body: TokenObtainPair;
  path?: never;
  query?: never;
  url: "/api/token/";
};

export type TokenCreateResponses = {
  200: TokenObtainPair;
};

export type TokenCreateResponse =
  TokenCreateResponses[keyof TokenCreateResponses];

export type TokenRefreshCreateData = {
  body: TokenRefreshWritable;
  path?: never;
  query?: never;
  url: "/api/token/refresh/";
};

export type TokenRefreshCreateResponses = {
  200: TokenRefresh;
};

export type TokenRefreshCreateResponse =
  TokenRefreshCreateResponses[keyof TokenRefreshCreateResponses];

export type TokenVerifyCreateData = {
  body: TokenVerify;
  path?: never;
  query?: never;
  url: "/api/token/verify/";
};

export type TokenVerifyCreateResponses = {
  200: TokenVerify;
};

export type TokenVerifyCreateResponse =
  TokenVerifyCreateResponses[keyof TokenVerifyCreateResponses];
